---
name: Wiki.JS
version: 1.6.4.7
slug: wikijs
description: The most powerful and extensible open source Wiki software
url: https://github.com/FaserF/hassio-addons/tree/master/wiki.js
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
services:
  - mysql:need
startup: application
boot: auto
map:
  - ssl
ingress: true
ingress_port: 3000
init: false
panel_icon: mdi:wikipedia
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(error|warn|info|debug)?
  reset_database: bool?
